permalink: /blog/:year/:month/:day/:title
# Site wide configuration
name: Hash Code 2020, some problems(python, C++)
locale:           en_US
url:              http://lilyheasamiko.github.io/hashCode.github.io/blog


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
#page_ext: md

# Found in _blogs/
post_layout: post
#page_layout: page

# Format titles with titlecase?
titlecase: true
